Add Rheinbahn Düsseldorf Stadtbahn
Traewelling/line-colors pull request #41
Opened 2023-10-02 14:26 UTC by ChillLP

Buses and Trams i will add at a later date

2023-10-02 18:01 UTC, MrKrisKrisu requested changes
Schaust du bitte noch, dass die Tests einen grünen Haken zeigen? Neu ist, dass du bitte selbst auch die Quellen in der `sources.json` hinzufügst. Danke! :)

`unknown operator vrr-rheinbahn-stadtbahn in row 270`

2023-10-02 18:01 UTC, ChillLP commented
ok ^^

2023-10-04 09:49 UTC, ChillLP commented
Close #43

2023-10-04 10:48 UTC, marhei approved these changes

2023-10-04 12:16 UTC, MrKrisKrisu approved these changes

2023-10-04 12:17 UTC, merged